import { useCallback, useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FiBarChart2, FiInfo, FiRefreshCw } from "react-icons/fi";
import EmptyState from "../../components/common/EmptyState";
import { getBusinessIntelligence } from "../../services/businessIntelligenceService";
import { currency } from "../../utils/format";

const ranges = [
  ["today", "Today"], ["yesterday", "Yesterday"], ["last_7_days", "Last 7 Days"], ["last_30_days", "Last 30 Days"], ["this_month", "This Month"], ["last_month", "Last Month"], ["custom", "Custom"],
];
const number = (value) => new Intl.NumberFormat("en-IN").format(Number(value || 0));
const Growth = ({ growth }) => <span className={growth?.type === "negative" ? "text-rose-600" : growth?.type === "positive" ? "text-emerald-600" : "text-slate-500"}>{growth?.label === "New" ? "New activity" : `${growth?.label || "—"} vs previous`}</span>;
const Card = ({ label, metric, currencyValue = true, definition }) => <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><span title={definition} className="text-slate-400"><FiInfo /></span></div><p className="mt-2 text-2xl font-bold text-slate-900">{currencyValue ? currency(metric?.current) : number(metric?.current)}</p><p className="mt-1 text-xs"><Growth growth={metric?.growth} /></p></article>;
const Panel = ({ title, children }) => <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="text-base font-bold text-slate-900">{title}</h3>{children}</section>;

const BusinessIntelligence = () => {
  const [range, setRange] = useState("last_30_days"); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => {
    if (range === "custom" && (!startDate || !endDate)) return;
    setLoading(true); setError("");
    try { const response = await getBusinessIntelligence({ range, ...(range === "custom" ? { startDate, endDate } : {}) }); setData(response.data?.data || null); }
    catch (err) { const message = err?.response?.data?.message || "Unable to load business intelligence"; setError(message); toast.error(message); }
    finally { setLoading(false); }
  }, [range, startDate, endDate]);
  useEffect(() => { const timer = setTimeout(load, 150); return () => clearTimeout(timer); }, [load]);
  const overview = data?.overview || {}; const sales = data?.sales || {}; const payments = data?.payments || {}; const menu = data?.menu || {}; const customers = data?.customers || {}; const operations = data?.operations || {}; const hasData = Number(overview.orders?.current || 0) > 0 || Number(payments.transactions || 0) > 0;
  return <div className="space-y-4 pb-20"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-bold text-slate-900 sm:text-2xl"><FiBarChart2 />Business Intelligence</h2><p className="mt-1 text-sm text-slate-500">Deterministic operational and financial analytics from your restaurant records.</p></div><button onClick={load} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm text-slate-700 disabled:opacity-60"><FiRefreshCw />Refresh</button></div>
    <section className="grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium text-slate-700">Period<select value={range} onChange={(event) => setRange(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2">{ranges.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{range === "custom" ? <><label className="text-sm font-medium text-slate-700">From<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="text-sm font-medium text-slate-700">To<input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label></> : null}<p className="self-end pb-2 text-xs text-slate-500">Business timezone: {data?.period?.timeZone || "—"}</p></section>
    {error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-center"><p className="font-semibold text-rose-700">{error}</p><button onClick={load} className="mt-3 rounded-lg bg-rose-600 px-4 py-2 text-sm font-medium text-white">Retry</button></div> : loading ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl bg-slate-100" />)}</div> : !hasData ? <EmptyState icon={<FiBarChart2 className="h-10 w-10" />} title="No business data for this period" description="Try another period or complete orders to begin seeing business insights." /> : <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Card label="Gross Sales" metric={overview.grossSales} definition={data?.definitions?.grossSales?.formula} /><Card label="Net Sales" metric={overview.netSales} definition={data?.definitions?.netSales?.formula} /><Card label="Net Collected" metric={overview.netCollected} definition={data?.definitions?.netCollected?.formula} /><Card label="Orders" metric={overview.orders} currencyValue={false} definition="Completed or served non-cancelled orders." /><Card label="Average Order Value" metric={overview.averageOrderValue} definition={data?.definitions?.averageOrderValue?.formula} /><Card label="Refunds" metric={overview.refunds} definition="Recorded refunded amounts for successful payments." /></div>
      <div className="grid gap-4 xl:grid-cols-2"><Panel title="Sales trend"><div className="mt-3 h-72">{sales.trend?.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={sales.trend}><XAxis dataKey="label" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip formatter={(value) => currency(value)} /><Bar dataKey="sales" fill="#047857" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer> : <p className="pt-16 text-center text-sm text-slate-500">No sales trend for this period.</p>}</div></Panel><Panel title="Order source mix"><div className="mt-3 space-y-2">{sales.sources?.length ? sales.sources.map((row) => <div key={row.source} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{row.source.replaceAll("_", " ")}</span><strong>{number(row.orders)} orders · {currency(row.sales)}</strong></div>) : <p className="text-sm text-slate-500">No order-source data.</p>}</div></Panel></div>
      <div className="grid gap-4 xl:grid-cols-2"><Panel title="Top menu items by quantity"><div className="mt-3 space-y-2">{menu.topItems?.length ? menu.topItems.map((row) => <div key={`${row.item}-${row.category}`} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm"><span><strong>{row.item}</strong><small className="ml-2 text-slate-500">{row.category}</small></span><span>{number(row.quantity)} units · <strong>{currency(row.sales)}</strong></span></div>) : <p className="text-sm text-slate-500">No item sales.</p>}</div></Panel><Panel title="Payment & reconciliation"><div className="mt-3 space-y-2">{payments.paymentMix?.map((row) => <div key={row.method} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{row.method.replaceAll("_", " ")}</span><strong>{currency(row.amount)} · {number(row.transactions)} txns</strong></div>)}<div className="grid grid-cols-3 gap-2 pt-2 text-center text-xs"><span>Unreconciled<br /><strong>{number(payments.reconciliation?.unreconciledPayments)}</strong></span><span>Cash mismatches<br /><strong>{number(payments.reconciliation?.cashMismatchCount)}</strong></span><span>Pending refunds<br /><strong>{number(payments.reconciliation?.pendingRefunds)}</strong></span></div></div></Panel></div>
      <div className="grid gap-4 lg:grid-cols-3"><Panel title="Customers"><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><p>Identified<br /><strong>{number(customers.identifiedCustomers)}</strong></p><p>New<br /><strong>{number(customers.newCustomers)}</strong></p><p>Returning<br /><strong>{number(customers.returningCustomers)}</strong></p><p>Repeat rate<br /><strong>{number(customers.repeatRate)}%</strong></p></div></Panel><Panel title="Operations"><div className="mt-3 space-y-2 text-sm"><p>Peak hours: {sales.peakHours?.map((row) => `${String(row.hour).padStart(2, "0")}:00`).join(", ") || "—"}</p><p>KOT timestamp quality: {operations.kitchen?.preparationTimeAvailable ? "available" : "duration unavailable"}</p><p>Tables with completed orders: {number(operations.tables?.length)}</p></div></Panel><Panel title="Inventory data quality"><div className="mt-3 space-y-2 text-sm"><p>Current stock value: <strong>{currency(operations.inventory?.currentStockValue)}</strong></p><p>Low stock: <strong>{number(operations.inventory?.lowStockCount)}</strong></p><p className="text-slate-500">{operations.inventory?.note}</p></div></Panel></div>
    </>}</div>;
};

export default BusinessIntelligence;
