import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { FiMapPin, FiPlus, FiPower } from "react-icons/fi";
import { createOutlet, getOutlets, updateOutletStatus } from "../../services/outletService";

const empty = { name: "", code: "", address: "", city: "", timeZone: "Asia/Kolkata" };
const Outlets = () => {
  const [outlets, setOutlets] = useState([]); const [form, setForm] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const { data } = await getOutlets(); setOutlets(data?.data || []); } catch (error) { toast.error(error?.response?.data?.message || "Unable to load outlets"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await createOutlet(form); setForm(empty); toast.success("Outlet created"); load(); } catch (error) { toast.error(error?.response?.data?.message || "Unable to create outlet"); } finally { setSaving(false); } };
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold text-slate-900">Outlets</h1><p className="mt-1 text-sm text-slate-500">Manage authorized branches without duplicating your restaurant business.</p></div><form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-5"><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Outlet name" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><input required value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} placeholder="Code" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><input value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} placeholder="City" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} placeholder="Address" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><button disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60"><FiPlus/>Add outlet</button></form><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{loading ? <div className="h-28 animate-pulse rounded-2xl bg-slate-200"/> : outlets.map((outlet) => <article key={outlet._id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold text-slate-900"><FiMapPin className="text-emerald-700"/>{outlet.name}</h2><p className="mt-1 text-sm text-slate-500">{outlet.code} · {outlet.city || "Location not set"}</p></div><span className={`rounded-full px-2 py-1 text-xs font-semibold ${outlet.isActive ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{outlet.isActive ? "Active" : "Inactive"}</span></div><button onClick={async () => { try { await updateOutletStatus(outlet._id, !outlet.isActive); load(); } catch (error) { toast.error(error?.response?.data?.message || "Unable to update outlet"); } }} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm"><FiPower/>{outlet.isActive ? "Deactivate" : "Activate"}</button></article>)}</div></div>;
};
export default Outlets;
