import api from "./api";

export const getPayments = (params = {}) => api.get("/payments", { params });
export const getPaymentById = (id) => api.get(`/payments/${id}`);
export const getPaymentByOrderId = (orderId) => api.get(`/payments/order/${orderId}`);
export const getOrderPaymentSummary = (orderId) => api.get(`/payments/order/${orderId}/summary`);
export const getPaymentStats = (params = {}) => api.get("/payments/stats", { params });
export const getPaymentReceipt = (id) => api.get(`/payments/${id}/receipt`, { responseType: "blob" });
export const refundPayment = (id, payload, idempotencyKey) => api.post(`/payments/${id}/refund`, payload, { headers: { "Idempotency-Key": idempotencyKey } });
export const deletePayment = (id) => api.delete(`/payments/${id}`);
export const exportPayments = (params = {}) => api.get("/payments/export", { params, responseType: "blob" });
export const createGatewayPayment = (payload, idempotencyKey) => api.post("/payments/create-order", payload, { headers: idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {} });
export const verifyGatewayPayment = (payload, idempotencyKey) => api.post("/payments/verify", payload, { headers: idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {} });
export const createCashfreePayment = (orderId, idempotencyKey) => api.post("/payments/cashfree/create-order", { orderId }, { headers: idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {} });
export const getCashfreePaymentStatus = (cashfreeOrderId) => api.get(`/payments/cashfree/${encodeURIComponent(cashfreeOrderId)}/status`);
export const getReconciliationSummary = () => api.get("/reconciliation/summary");
export const getReconciliationBills = (params = {}) => api.get("/reconciliation/bills", { params });
export const getCashReconciliationPreview = () => api.get("/reconciliation/cash/preview");
export const closeCashReconciliation = (payload) => api.post("/reconciliation/cash/close", payload);
export const reconcilePayment = (id, payload = {}) => api.patch(`/reconciliation/payments/${id}/reconcile`, payload);
