import mongoose from "mongoose";
import Restaurant from "../models/Restaurant.js"; import Outlet from "../models/Outlet.js"; import User from "../models/User.js"; import Staff from "../models/Staff.js"; import Table from "../models/Table.js"; import Reservation from "../models/Reservation.js"; import Category from "../models/Category.js"; import Food from "../models/Food.js"; import KitchenStation from "../models/KitchenStation.js"; import Order from "../models/Order.js"; import KotTicket from "../models/KotTicket.js"; import Payment from "../models/Payment.js"; import Invoice from "../models/Invoice.js"; import Inventory from "../models/Inventory.js"; import StockMovement from "../models/StockMovement.js"; import Recipe from "../models/Recipe.js"; import LoyaltySettings from "../models/LoyaltySettings.js"; import LoyaltyAccount from "../models/LoyaltyAccount.js"; import LoyaltyTransaction from "../models/LoyaltyTransaction.js"; import Notification from "../models/Notification.js"; import Subscription from "../models/Subscription.js"; import IntelligenceInsight from "../models/IntelligenceInsight.js";
import { calculateOrderAmounts } from "../services/orderCalculationService.js"; import { syncKotForOrder } from "../services/kotService.js";

const DB = "restosphere_demo_local", PORT = "27029";
const fail = (message) => { throw new Error(message); };
const now = (days, hour = 13) => { const d = new Date(); d.setDate(d.getDate() - days); d.setHours(hour, (days * 7) % 55, 0, 0); return d; };
const stamp = (Model, id, date) => Model.updateOne({ _id: id }, { $set: { createdAt: date, updatedAt: date } });
const assert = (ok, text) => { if (!ok) fail(`Demo verification failed: ${text}`); };
const guard = () => {
  if (String(process.env.NODE_ENV).toLowerCase() !== "demo" || process.env.DEMO_CONFIRM !== "RESTOSPHERE_LOCAL_DEMO") fail("Refusing demo reset without NODE_ENV=demo and DEMO_CONFIRM=RESTOSPHERE_LOCAL_DEMO.");
  const uri = String(process.env.DEMO_MONGO_URI || ""), password = String(process.env.DEMO_ADMIN_PASSWORD || ""); let parsed; try { parsed = new URL(uri); } catch { fail("DEMO_MONGO_URI must be a valid loopback mongodb URI."); }
  const host = String(parsed.hostname).replace(/^\[|\]$/g, "").toLowerCase(), name = decodeURIComponent(parsed.pathname).replace(/^\/+/, "").split("/")[0];
  if (parsed.protocol !== "mongodb:" || !["127.0.0.1", "localhost", "::1"].includes(host) || (parsed.port || "27017") !== PORT || name !== DB) fail(`Demo reset is locked to loopback port ${PORT} / ${DB}.`);
  if (password.length < 12) fail("DEMO_ADMIN_PASSWORD must be at least 12 characters; it is not stored in source.");
  for (const appUri of [process.env.MONGO_URI, process.env.MONGODB_URI]) if (appUri && String(appUri) !== uri) fail("Application Mongo configuration differs from the locked demo URI.");
  return { uri, password };
};
const { uri, password } = guard();
try {
  await mongoose.connect(uri, { serverSelectionTimeoutMS: 5000 }); const hello = await mongoose.connection.db.admin().command({ hello: 1 }); assert(hello.isWritablePrimary && hello.setName === "rsRestoSphereDemo" && mongoose.connection.name === DB, "not the writable local demo replica set"); await mongoose.connection.db.dropDatabase();
  const restaurant = await Restaurant.create({ name: "RestoSphere Demo Restaurant", slug: "restosphere-demo-restaurant", branchCode: "RSD-LOCAL", address: "18 Market Walk, Demo District", city: "Riverton", state: "Karnataka", gstRate: 5, onlineOrdersEnabled: true, timeZone: "Asia/Kolkata" });
  const [main, city] = await Outlet.create([{ restaurant: restaurant._id, name: "Main Outlet", code: "MAIN", address: "18 Market Walk", city: "Riverton", isActive: true, isDefault: true }, { restaurant: restaurant._id, name: "City Center Outlet", code: "CITY", address: "42 Central Avenue", city: "Riverton", isActive: true }]);
  const admin = await User.create({ fullName: "Demo Operations Admin", email: "demo.admin@restosphere.invalid", phone: "9000000100", password, role: "admin", restaurant: restaurant._id, defaultOutlet: main._id, outletAccess: [{ outlet: main._id, role: "admin" }, { outlet: city._id, role: "admin" }], isActive: true });
  const staffUsers = [admin, ...(await User.create([["Demo Chef", "demo.chef@restosphere.invalid", "chef"], ["Demo Waiter", "demo.waiter@restosphere.invalid", "waiter"], ["Demo Cashier", "demo.cashier@restosphere.invalid", "cashier"]].map(([fullName, email, role], i) => ({ fullName, email, phone: `900000011${i + 1}`, password, role, restaurant: restaurant._id, defaultOutlet: main._id, outletAccess: [{ outlet: main._id, role }], isActive: true }))))];
  await Subscription.create({ restaurant: restaurant._id, planName: "Demo Professional", price: 0, status: "active", startDate: now(60), subscriptionStartAt: now(60), subscriptionEndAt: now(-365), renewalDate: now(-365), metadata: { localDemo: true } });
  const stations = await KitchenStation.create([{ name: "Hot Kitchen", restaurant: restaurant._id, sortOrder: 1 }, { name: "Beverage Bar", restaurant: restaurant._id, sortOrder: 2 }]);
  const names = ["Starters", "Main Course", "Breads", "Rice", "Beverages", "Desserts"], categories = Object.fromEntries((await Category.create(names.map((name) => ({ restaurant: restaurant._id, name, slug: name.toLowerCase().replaceAll(" ", "-"), active: true })))).map((x) => [x.name, x]));
  const source = [["Starters","Paneer Tikka",345,0],["Starters","Crispy Corn",295,0],["Starters","Veg Seekh Kebab",325,0],["Main Course","Paneer Butter Masala",385,0],["Main Course","Dal Makhani",315,0],["Main Course","Vegetable Korma",335,0],["Breads","Butter Naan",65,0],["Breads","Tandoori Roti",40,0],["Breads","Garlic Naan",85,0],["Rice","Jeera Rice",185,0],["Rice","Vegetable Biryani",365,0],["Rice","Steamed Rice",135,0],["Beverages","Masala Chaas",95,1],["Beverages","Fresh Lime Soda",125,1],["Beverages","Cold Coffee",165,1],["Desserts","Gulab Jamun",125,0],["Desserts","Sizzling Brownie",245,0],["Desserts","Kulfi Falooda",195,0]];
  const foods = Object.fromEntries((await Food.create(source.map(([category, name, price, station]) => ({ restaurant: restaurant._id, category: categories[category]._id, name, price, description: `Fictional demo ${name}`, preparationTime: station ? 8 : 18, isAvailable: true, kitchenStation: stations[station]._id })))).map((x) => [x.name, x]));
  const tables = await Table.create(Array.from({ length: 12 }, (_, i) => ({ restaurant: restaurant._id, outlet: main._id, tableNumber: `Table ${i + 1}`, capacity: i % 4 === 0 ? 6 : 4, floor: "Ground Floor", section: i < 8 ? "Main Dining" : "Garden", shape: i % 2 ? "SQUARE" : "RECTANGLE", status: i < 7 ? "AVAILABLE" : i < 10 ? "OCCUPIED" : i === 10 ? "RESERVED" : "MAINTENANCE" })));
  await Table.create(Array.from({ length: 4 }, (_, i) => ({ restaurant: restaurant._id, outlet: city._id, tableNumber: `City Table ${i + 1}`, capacity: 4, floor: "Level 1", section: "City Dining", shape: "SQUARE", status: "AVAILABLE" })));
  const roles = [["Meera","Shah","MANAGER","Management","ON_DUTY"],["Kabir","Kapoor","CHEF","Kitchen","BUSY"],["Tara","Iyer","WAITER","Service","ON_DUTY"],["Dev","Malhotra","CASHIER","Billing","ON_DUTY"]];
  await Staff.create(roles.map(([firstName,lastName,role,department,dutyStatus],i) => ({ employeeId: `DEMO-${i + 1}`, user: staffUsers[i]._id, firstName, lastName, role, department, phone: `900000020${i + 1}`, email: `staff${i + 1}@restosphere.invalid`, restaurant: restaurant._id, outlet: main._id, joiningDate: now(240 - i * 15), status: "ACTIVE", dutyStatus, shiftStartedAt: now(0,9), lastDutyActivityAt: now(0,12) })));
  const customers = await User.create(["Aarav Mehta","Isha Verma","Rohan Das","Kiara Singh","Neil Arora","Sana Kapoor","Arjun Rao","Mira Joshi"].map((fullName,i) => ({ fullName, email: `guest${i + 1}@example.invalid`, phone: `90000003${String(i + 1).padStart(2,"0")}`, password, role: "customer", customerRestaurants: [{ restaurant: restaurant._id }], tags: [{ restaurant: restaurant._id, name: i % 2 ? "Repeat guest" : "Dining club" }], customerNotes: [{ restaurant: restaurant._id, createdBy: admin._id, text: "Fictional local demo profile." }] })));
  await Reservation.create({ customer: customers[0]._id, table: tables[10]._id, restaurant: restaurant._id, outlet: main._id, date: now(-1,20), guests: 4, status: "confirmed", notes: "Fictional demo reservation" });
  const stock = [["Paneer","ING-PANEER",24,"kg",8,320],["Basmati Rice","ING-RICE",36,"kg",12,110],["Whole Wheat Flour","ING-FLOUR",28,"kg",10,48],["Tomato","ING-TOMATO",5,"kg",8,42],["Onion","ING-ONION",22,"kg",8,38],["Cooking Oil","ING-OIL",18,"l",6,155],["Cold Coffee Beans","ING-COFFEE",0,"kg",2,620]];
  const inventory = Object.fromEntries((await Inventory.create(stock.map(([itemName,sku,quantity,unit,reorderLevel,costPerUnit]) => ({ restaurant: restaurant._id, outlet: main._id, itemName, sku, quantity, unit, baseUnit: unit, minStock: reorderLevel / 2, reorderLevel, costPerUnit, category: "Kitchen", storageLocation: "Main Store" })))).map((x) => [x.itemName,x]));
  await StockMovement.create(Object.values(inventory).map((x) => ({ restaurant: restaurant._id, outlet: main._id, inventoryItem: x._id, movementType: "OPENING_STOCK", quantity: x.quantity, unit: x.baseUnit, previousStock: 0, newStock: x.quantity, idempotencyKey: `demo-opening-${x.sku}`, reason: "Fictional demo opening stock", user: admin._id })));
  const recipe = (food, name, ingredients) => ({ restaurant: restaurant._id, food: foods[food]._id, name, version: 1, status: "ACTIVE", yieldQuantity: 1, yieldUnit: "portion", ingredients, createdBy: admin._id, updatedBy: admin._id });
  await Recipe.create([recipe("Paneer Butter Masala","Paneer Butter Masala Standard",[{inventoryItem:inventory.Paneer._id,quantity:180,unit:"g"},{inventoryItem:inventory.Tomato._id,quantity:120,unit:"g"},{inventoryItem:inventory["Cooking Oil"]._id,quantity:25,unit:"ml"}]),recipe("Vegetable Biryani","Vegetable Biryani Standard",[{inventoryItem:inventory["Basmati Rice"]._id,quantity:180,unit:"g"},{inventoryItem:inventory.Onion._id,quantity:80,unit:"g"}]),recipe("Butter Naan","Butter Naan Standard",[{inventoryItem:inventory["Whole Wheat Flour"]._id,quantity:90,unit:"g"}]),recipe("Cold Coffee","Cold Coffee Standard",[{inventoryItem:inventory["Cold Coffee Beans"]._id,quantity:18,unit:"g"}])]);
  const createOrder = async ({ number, outlet, customer, table, items, status, paid, method, date, source = "DINE_IN", kitchen = "COMPLETED" }) => {
    const amount = calculateOrderAmounts({ items, gstRate: 5, orderType: source === "ONLINE" ? "DELIVERY" : "DINE_IN", deliveryCharge: source === "ONLINE" ? 45 : 0 });
    const order = await Order.create({ orderNumber: number, restaurant: restaurant._id, outlet: outlet._id, customer: customer._id, table: table?._id || null, orderType: source === "ONLINE" ? "DELIVERY" : "DINE_IN", orderSource: source, items: amount.items.map((x) => ({ ...x, kitchenStatus: kitchen === "COMPLETED" ? "SERVED" : kitchen === "PENDING" ? "NEW" : kitchen })), ...amount, paymentMethod: method, paymentStatus: paid ? "PAID" : "PENDING", status, kitchenStatus: kitchen, paidAt: paid ? date : null, completedAt: status === "COMPLETED" ? date : null, createdBy: admin._id, statusHistory: [{ status, changedBy: admin._id, changedAt: date }] });
    await stamp(Order, order._id, date); return order;
  };
  const cycle = [foods["Paneer Butter Masala"],foods["Vegetable Biryani"],foods["Dal Makhani"],foods["Paneer Tikka"],foods["Jeera Rice"],foods["Cold Coffee"],foods["Gulab Jamun"]], historical = [];
  for (let i = 0; i < 30; i += 1) {
    const outlet = i % 6 === 0 ? city : main, online = i % 5 === 0, date = now(29 - i, 12 + i % 8), first = cycle[i % cycle.length], second = cycle[(i + 2) % cycle.length];
    const order = await createOrder({ number: `DEMO-H-${String(i + 1).padStart(3,"0")}`, outlet, customer: customers[i % customers.length], table: online || outlet._id.equals(city._id) ? null : tables[i % 7], items: [{ menuItem:first._id,name:first.name,price:first.price,quantity:1 + i % 2 },{ menuItem:second._id,name:second.name,price:second.price,quantity:1 }], status:"COMPLETED", paid:true, method:i % 3 === 0 ? "CASH" : i % 3 === 1 ? "CREDIT_CARD" : "UPI", date, source:online ? "ONLINE" : "DINE_IN" }); historical.push(order);
    const payment = await Payment.create({ paymentId:`DEMO-PAY-${String(i + 1).padStart(4,"0")}`, orderId:order._id, customerId:order.customer, tableId:order.table, restaurant:restaurant._id, outlet:outlet._id, amount:order.total, subtotal:order.subtotal, tax:order.tax, discount:order.discount, serviceCharge:order.serviceCharge, totalAmount:order.total, paymentMethod:order.paymentMethod, paymentStatus:"PAID", transactionId:`DEMO-LEDGER-${String(i + 1).padStart(4,"0")}`, idempotencyKey:`demo-payment-${i + 1}`, paidAt:date, receivedBy:admin._id, reconciliationStatus:"RECONCILED", reconciledAt:date, reconciledBy:admin._id, timeline:[{status:"PAID",timestamp:date,note:"Fictional local demo settlement"}] }); await stamp(Payment,payment._id,date);
    const invoice = await Invoice.create({ invoiceNumber:`DEMO-INV-${String(i + 1).padStart(4,"0")}`, order:order._id, restaurant:restaurant._id, issuedAt:date, items:order.items.map((x)=>({name:x.name,quantity:x.quantity,price:x.price,subtotal:x.subtotal,taxableAmount:x.subtotal})), gstType:order.gstType,gstRate:order.gstRate,subtotal:order.subtotal,cgst:order.cgst,sgst:order.sgst,igst:order.igst,totalTax:order.tax,total:order.total,totalPaid:order.total,netTotal:order.total,netTax:order.tax,paymentBreakdown:[{paymentId:payment.paymentId,paymentMethod:payment.paymentMethod,amount:payment.amount,paidAt:date}],status:"FINAL" }); await stamp(Invoice,invoice._id,date);
  }
  const live = [[7,"DEMO-LIVE-001","PENDING","PENDING",foods["Paneer Tikka"],customers[1]],[8,"DEMO-LIVE-002","PREPARING","PREPARING",foods["Vegetable Biryani"],customers[2]],[9,"DEMO-LIVE-003","READY","READY",foods["Paneer Butter Masala"],customers[3]]];
  for (const [tableIndex,number,status,kitchen,food,customer] of live) { const order = await createOrder({ number,outlet:main,customer,table:tables[tableIndex],items:[{menuItem:food._id,name:food.name,price:food.price,quantity:1},{menuItem:foods["Butter Naan"]._id,name:"Butter Naan",price:foods["Butter Naan"].price,quantity:2}],status,paid:false,method:"CASH",date:now(0,12),kitchen }); await syncKotForOrder(order); await Table.updateOne({_id:tables[tableIndex]._id},{$set:{currentOrder:order._id,status:"OCCUPIED"}}); }
  await LoyaltySettings.create({ restaurant:restaurant._id,enabled:true,spendPerPoint:100,pointValue:0.5,minimumRedemptionPoints:100,maxRedemptionPercent:25 });
  for(let i=0;i<customers.length;i+=1){const points=160+i*85, account=await LoyaltyAccount.create({customer:customers[i]._id,restaurant:restaurant._id,currentPoints:points,lifetimeEarnedPoints:points+100,lifetimeRedeemedPoints:100,status:"ACTIVE",joinedAt:now(120-i*5),lastActivityAt:now(i%5)}); await LoyaltyTransaction.create({account:account._id,customer:customers[i]._id,restaurant:restaurant._id,type:"EARN",points,previousBalance:0,newBalance:points,order:historical[i]._id,reason:"Fictional demo order points",createdBy:admin._id,eventKey:`demo-loyalty-${i+1}`});}
  await Notification.create([{restaurantId:restaurant._id,outlet:main._id,user:admin._id,type:"INVENTORY_LOW",eventType:"INVENTORY_LOW",category:"INVENTORY",severity:"WARNING",title:"Low stock attention",message:"Fictional demo inventory contains a low-stock item.",route:"/dashboard/admin/inventory"},{restaurantId:restaurant._id,outlet:main._id,user:admin._id,type:"KOT_CREATED",eventType:"KOT_CREATED",category:"OPERATIONS",severity:"INFO",title:"Kitchen tickets ready",message:"Three fictional demo KOT tickets are available.",route:"/dashboard/admin/kitchen"}]);
  await IntelligenceInsight.create({restaurant:restaurant._id,signalKey:"demo-inventory-attention",category:"INVENTORY",severity:"ATTENTION",status:"ACTIVE",title:"Review low stock items",summary:"Fictional demo inventory includes low-stock items for operational review.",evidence:[{metric:"Low stock items",current:2,baseline:0,change:2,unit:"items"}],recommendedActions:["Review inventory before peak service."],confidence:"HIGH",dataPeriod:{range:"last_30_days",start:now(29),end:now(-1)},generatedAt:now(0,10)});
  const [mainTables,cityTables,categoriesCount,menuCount,customerCount,historicalCount,liveCount,staffCount,inventoryCount,recipeCount,paymentCount,invoiceCount,kotCount,onlineCount] = await Promise.all([Table.countDocuments({restaurant:restaurant._id,outlet:main._id}),Table.countDocuments({restaurant:restaurant._id,outlet:city._id}),Category.countDocuments({restaurant:restaurant._id}),Food.countDocuments({restaurant:restaurant._id}),User.countDocuments({role:"customer","customerRestaurants.restaurant":restaurant._id}),Order.countDocuments({restaurant:restaurant._id,orderNumber:/^DEMO-H-/}),Order.countDocuments({restaurant:restaurant._id,orderNumber:/^DEMO-LIVE-/}),Staff.countDocuments({restaurant:restaurant._id,status:"ACTIVE"}),Inventory.countDocuments({restaurant:restaurant._id}),Recipe.countDocuments({restaurant:restaurant._id,status:"ACTIVE"}),Payment.countDocuments({restaurant:restaurant._id,paymentStatus:"PAID"}),Invoice.countDocuments({restaurant:restaurant._id,status:"FINAL"}),KotTicket.countDocuments({restaurant:restaurant._id}),Order.countDocuments({restaurant:restaurant._id,orderSource:"ONLINE"})]);
  const [revenue] = await Invoice.aggregate([{ $match:{restaurant:restaurant._id,status:"FINAL"} },{$group:{_id:null,total:{$sum:"$netTotal"}}}]);
  assert(mainTables===12 && cityTables===4,"table counts"); assert(categoriesCount===6 && menuCount===18,"menu counts"); assert(customerCount===8 && historicalCount===30 && liveCount===3,"customer/order counts"); assert(staffCount===4 && inventoryCount===7 && recipeCount===4,"staff/inventory counts"); assert(paymentCount===30 && invoiceCount===30 && kotCount===3 && onlineCount>0 && Number(revenue?.total)>0,"ledger/KDS/report data");
  console.log(JSON.stringify({status:"READY",database:DB,hostClass:"loopback-only",replicaSet:"rsRestoSphereDemo",restaurant:restaurant.name,outlets:{main:main.name,city:city.name},counts:{tables:{main:mainTables,city:cityTables},categories:categoriesCount,menuItems:menuCount,customers:customerCount,historicalOrders:historicalCount,liveOrders:liveCount,staff:staffCount,inventory:inventoryCount,recipes:recipeCount,paidPayments:paymentCount,invoices:invoiceCount,kdsTickets:kotCount,onlineOrders:onlineCount},invoiceRevenue:Number(revenue.total)}));
} finally { await mongoose.disconnect().catch(()=>{}); }
