import test from "node:test";
import assert from "node:assert/strict";
import { calculateOrderAmounts } from "../services/orderCalculationService.js";
import { assertTableTransition, deriveTableLifecycle } from "../services/lifecycleService.js";
import { assertOrderTableConsistency, inspectTableOrderConsistency } from "../services/posValidationService.js";
import { assertVerifiedSettlement } from "../services/posIntegrityService.js";

const id = "507f1f77bcf86cd799439011";
const table = (status = "AVAILABLE") => ({ _id: id, status, currentOrder: null, activeOrderCount: 0 });
const order = (overrides = {}) => ({ _id: id, status: "PENDING", paymentStatus: "PENDING", billingStatus: "UNBILLED", isArchived: false, ...overrides });

test("01 lifecycle starts AVAILABLE", () => assert.equal(deriveTableLifecycle({ table: table(), orders: [] }), "AVAILABLE"));
test("02 pending order means ORDER_CREATED", () => assert.equal(deriveTableLifecycle({ table: table(), orders: [order()] }), "ORDER_CREATED"));
test("03 accepted order means OCCUPIED", () => assert.equal(deriveTableLifecycle({ table: table(), orders: [order({ status: "CONFIRMED" })] }), "OCCUPIED"));
test("04 billed order means BILL", () => assert.equal(deriveTableLifecycle({ table: table(), orders: [order({ billingStatus: "BILLED" })] }), "BILL"));
test("05 verified payment means PAYMENT_VERIFIED", () => assert.equal(deriveTableLifecycle({ table: table(), orders: [order({ paymentStatus: "PAYMENT_VERIFIED" })] }), "PAYMENT_VERIFIED"));
test("06 settled order releases table", () => assert.equal(deriveTableLifecycle({ table: table("PAID"), orders: [order({ status: "COMPLETED", paymentStatus: "PAID" })] }), "AVAILABLE"));
test("07 invalid table jump is rejected", () => assert.throws(() => assertTableTransition("AVAILABLE", "PAID"), { statusCode: 409 }));
test("08 cancellation may release occupied table", () => assert.equal(assertTableTransition("OCCUPIED", "AVAILABLE"), "AVAILABLE"));
test("09 dine-in requires a table", () => assert.throws(() => assertOrderTableConsistency({ orderType: "DINE_IN", table: null }), { statusCode: 422 }));
test("10 takeaway cannot carry a table", () => assert.throws(() => assertOrderTableConsistency({ orderType: "TAKEAWAY", table: id }), { statusCode: 422 }));
test("11 cross-tenant table is rejected", () => assert.throws(() => assertOrderTableConsistency({ orderType: "DINE_IN", table: id, restaurant: id, tableRestaurant: "507f191e810c19729de860ea" }), { statusCode: 403 }));
test("12 calculation uses server item prices", () => assert.equal(calculateOrderAmounts({ items: [{ price: 50, quantity: 2 }], taxPercent: 5 }).total, 105));
test("13 discount cannot exceed subtotal", () => assert.equal(calculateOrderAmounts({ items: [{ price: 50, quantity: 1 }], discount: 99 }).total, 0));
test("14 non-delivery cannot add delivery charge", () => assert.equal(calculateOrderAmounts({ items: [{ price: 50, quantity: 1 }], deliveryCharge: 40, orderType: "DINE_IN" }).total, 50));
test("15 delivery keeps delivery charge", () => assert.equal(calculateOrderAmounts({ items: [{ price: 50, quantity: 1 }], deliveryCharge: 40, orderType: "DELIVERY" }).total, 90));
test("16 GST rate above 100 is rejected", () => assert.throws(() => calculateOrderAmounts({ items: [{ price: 1, quantity: 1 }], taxPercent: 101 }), { statusCode: 422 }));
test("17 service charge above 100 is rejected", () => assert.throws(() => calculateOrderAmounts({ items: [{ price: 1, quantity: 1 }], serviceChargePercent: 101 }), { statusCode: 422 }));
test("18 negative quantity is rejected", () => assert.throws(() => calculateOrderAmounts({ items: [{ price: 1, quantity: -1 }] }), { statusCode: 422 }));
test("19 cancelled order cannot be settled", () => assert.throws(() => assertVerifiedSettlement({ order: order({ status: "CANCELLED" }), provider: "cash", actor: { role: "cashier" } }), { statusCode: 409 }));
test("20 a paid order cannot settle twice", () => assert.throws(() => assertVerifiedSettlement({ order: order({ paymentStatus: "PAID" }), provider: "cash", actor: { role: "cashier" } }), { statusCode: 409 }));
test("21 waiter cannot verify cash", () => assert.throws(() => assertVerifiedSettlement({ order: order(), provider: "cash", actor: { role: "waiter" } }), { statusCode: 403 }));
test("22 cashier can verify cash", () => assert.doesNotThrow(() => assertVerifiedSettlement({ order: order(), provider: "cash", actor: { role: "cashier" } })));
test("23 payment tenant mismatch is rejected", () => assert.throws(() => assertVerifiedSettlement({ order: { ...order(), restaurant: id }, payment: { restaurant: "507f191e810c19729de860ea" }, provider: "cash", actor: { role: "cashier" } }), { statusCode: 409 }));
test("24 maintenance is retained", () => assert.equal(deriveTableLifecycle({ table: table("MAINTENANCE"), orders: [order({ status: "CONFIRMED" })] }), "MAINTENANCE"));
test("25 active sibling order prevents release", () => assert.equal(deriveTableLifecycle({ table: table(), orders: [order({ status: "COMPLETED", paymentStatus: "PAID" }), order({ _id: "507f191e810c19729de860ea", status: "CONFIRMED" })] }), "OCCUPIED"));
test("26 archived orders are ignored", () => assert.equal(deriveTableLifecycle({ table: table(), orders: [order({ isArchived: true, status: "CONFIRMED" })] }), "AVAILABLE"));
test("27 status checker catches an available active table", () => assert.equal(inspectTableOrderConsistency({ table: table(), orders: [order({ table: id })] }).valid, false));
test("28 status checker accepts ORDER_CREATED pending table", () => assert.equal(inspectTableOrderConsistency({ table: { ...table("ORDER_CREATED"), currentOrder: id, activeOrderCount: 1 }, orders: [order({ table: id })] }).valid, true));
test("29 status checker catches wrong current order", () => assert.equal(inspectTableOrderConsistency({ table: { ...table("ORDER_CREATED"), currentOrder: "507f191e810c19729de860ea", activeOrderCount: 1 }, orders: [order({ table: id })] }).errors.includes("CURRENT_ORDER_MISMATCH"), true));
test("30 paid table transition must pass verified state", () => assert.throws(() => assertTableTransition("BILL", "PAID"), { statusCode: 409 }));
